/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'ROUTEAI',systemName:'知华智能配送路线平台',englishName:'AI ROUTE PLANNING',theme:{primary:'#43677a',dark:'#243b48',accent:'#ce8643'},workspace:'物流中心 / 智能调度组',fieldWorkspace:'华东物流中心 / 城配调度台',period:'2026-08-19 · 当日配送',liveText:'交通、天气与车辆于 10:43 更新',fieldContextLabel:'当前波次',fieldContext:'华东城配 · 午间波次',fieldUser:'叶宁',fieldRole:'配送调度员',adminUser:'顾清',adminRole:'物流运营负责人',
 adminTitle:'智能配送调度中心',adminBreadcrumb:'物流运营 / 路线智能',adminSubtitle:'综合路网、天气、车辆载重、司机工时和冷链时窗，为每条配送路线提供可解释的发车建议。',exportAction:'导出调度日报',createAction:'新建路线任务',chartTitle:'配送准时率趋势',chartSubtitle:'实际准时率 / 运营目标',chartLabels:['06:00','08:00','10:00','12:00','14:00','16:00','18:00','20:00','22:00'],loadTitle:'区域配送负荷',loadSubtitle:'待发路线占调度容量',recordsTitle:'重点配送路线',recordsSubtitle:'按时效、交通、天气和冷链风险排序',issueTitle:'调度异常事件',issueSubtitle:'需要改线、换车或延迟发车',
 recordName:'路线任务',itemName:'配送区域',unitName:'调度团队',batchName:'路线策略',planName:'站点',doneName:'已完成',exceptionName:'异常',unitLabel:'站',listBreadcrumb:'配送调度 / 路线任务',listSubtitle:'管理车辆、司机、站点、时窗和路线风险，保留算法与人工调度轨迹。',listSummary:[['今日路线','286'],['配送站点','1,842'],['高风险','18',true],['准时率','94.6%']],tabs:['全部','待规划','待发车','配送中','已归档'],
 fieldBreadcrumb:'调度工作台 / 华东城配',fieldTitle:'配送路线调度工作台',fieldSubtitle:'待发路线 16 条 · 高风险 4 条 · 冷链任务 3 条',fieldSecondary:'查看实时路况',reportAction:'提交调度意见',fieldNoticeTitle:'地图与车辆链路正常',fieldNotice:'车辆在线率 98.8%',steps:['订单聚合','路线评分','安全校验','调度确认','执行复盘'],documentAction:'查看路线证据',printAction:'打印路单',resourceCardTitle:'调度数据资源',resourceValueLabel:'在线车辆',resourceHealthLabel:'车辆在线率',quickSubtitle:'常用调度入口',quickActions:[['调度反馈','/shopfloor/report','车辆、司机与改线意见'],['站点与时窗','/shopfloor/material','订单、站点和交付约束'],['调度资源','/shopfloor/resources','地图、车辆和天气服务'],['异常升级','/shopfloor/andon','冷链、工时和重大延误']],
 reportDefaults:[6,1],reportTitle:'路线调度反馈',reportSubtitle:'记录发车、改线、换车与延迟原因。',reportSuccess:'路线调度意见已提交',reportPlaceholder:'填写交通、天气、车辆、司机和客户时窗依据',reportFootnote:'司机工时超限和冷链超时路线不得自动发车',ruleTitle:'路线发车安全门禁',ruleSubtitle:'ROUTE-AI · V1.0',rules:[['司机工时','超限禁止发车'],['冷链时窗','超时必须改线'],['车辆超载','人工复核'],['重大天气','调度主管确认',true]],fieldTotals:[['16','待发路线'],['4','高风险路线'],['3','冷链任务'],['98.8%','车辆在线率']],
 adminMenus:[['/admin','home','配送调度中心'],['/admin/work-orders','order','路线任务'],['/admin/samples','box','站点与时窗'],['/admin/schedule','calendar','波次日历'],['/admin/methods','process','路线策略'],['/admin/reviews','quality','调度审批'],['/admin/resources','machine','车辆资源'],['/admin/report','chart','时效分析']],fieldMenus:[['/shopfloor','home','调度工作台'],['/shopfloor/report','report','调度反馈'],['/shopfloor/tasks','order','我的路线'],['/shopfloor/material','box','站点与时窗'],['/shopfloor/resources','machine','资源状态'],['/shopfloor/andon','risk','异常升级',4]],moduleTitles:{tasks:['我的路线任务','查看车辆、司机、时窗和风险'],material:['站点与时窗台账','查看订单、位置和交付要求'],resources:['调度资源中心','管理地图、交通、天气、车辆和司机'],andon:['配送异常升级','提交冷链、工时和重大延误'],samples:['路线样本库','维护历史路线、时效和异常结果'],schedule:['配送波次日历','协调订单截单和发车窗口'],methods:['路线策略','维护距离、时效、安全和冷链规则'],reviews:['调度审批','记录发车、改线和延迟决策'],report:['配送时效分析','分析准时率、里程、空驶和风险']},
 tagline:'让每一次发车，都兼顾时效、安全与执行条件',storyTitle:'路线不是地图上的一条线，<br/>而是一组真实的交付约束',storyText:'将交通、天气、车辆、司机和冷链放进同一套判断，让调度人员更早发现风险。',pattern:[2,5,8,11,14,17,20,23,26,29,31],loginStats:[['286','今日路线'],['94.6%','配送准时率'],['18','高风险路线']],loginTitle:'智能配送调度中心',adminDemo:'路线 / 车辆 / 时效',fieldDemo:'规划 / 调度 / 执行'}
export const records=[{no:'RT-260819-118',name:'上海城区多点配送',code:'EAST-URBAN-08',unit:'华东调度组',group:'华东物流中心',plan:42,done:31,exception:5,due:'11:20',batch:'拥堵+多站',status:'配送中',progress:74,priority:'关注'},{no:'RT-260819-112',name:'苏州工业园区专线',code:'SUZHOU-B2B-03',unit:'智能调度组',group:'B2B 物流',plan:26,done:18,exception:2,due:'12:00',batch:'B2B+时窗',status:'待发车',progress:69,priority:'正常'},{no:'RT-260819-106',name:'生鲜冷链跨城配送',code:'COLD-CHAIN-07',unit:'冷链调度组',group:'专业物流',plan:18,done:7,exception:6,due:'10:50',batch:'天气+冷链',status:'调度审批',progress:39,priority:'紧急'},{no:'RT-260819-099',name:'华东日常补货路线',code:'EAST-REGULAR-02',unit:'华东调度组',group:'华东物流中心',plan:34,done:34,exception:1,due:'09:45',batch:'稳定路线',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'MAP-01',name:'路网与交通服务',unit:'物流数据组',status:'运行中',health:99,value:'42',valueUnit:'ms',note:'P95 路径查询保持稳定'},{code:'FLEET-02',name:'车辆与司机连接器',unit:'车队运营组',status:'运行中',health:96,value:'186',valueUnit:'辆',note:'车辆在线率 98.8%'},{code:'WEATHER-03',name:'天气风险服务',unit:'调度支持组',status:'预警',health:89,value:'3',valueUnit:'区域',note:'午后强对流风险上升'}]
export const reviews=[{no:'RV-260819-032',title:'生鲜冷链跨城配送',type:'冷链路线审批',detail:'预计超时 28 分钟 · 顾清',result:'待确认'},{no:'RV-260819-027',title:'华东日常补货路线',type:'准时率复盘',detail:'准时率 98.2% · 叶宁',result:'通过'},{no:'RV-260819-018',title:'上海城区多点配送',type:'拥堵改线复核',detail:'高架拥堵指数 0.86',result:'异常'}]
export const adminMetrics=[['今日路线','286','覆盖 1,842 个站点','blue'],['配送准时率','94.6%','较上周 +1.1%','green'],['高风险路线','18','4 条等待调度审批','orange'],['冷链预警','7','3 条可能超出时窗','red']]
export const fieldMetrics=[['待发路线','16','4 条高风险','blue'],['今日已调度','48','改线 6 条','green'],['冷链任务','3','全部人工确认','orange'],['车辆在线率','98.8%','2 辆设备离线','slate']]
export const chartActual=[87,89,90,91,92,93,93,94,95],chartTarget=[90,91,92,93,94,95,95,96,97]
export const loads=[['上海城配',88,'待发 18 条'],['苏州园区',74,'待发 12 条'],['杭州城配',62,'待发 9 条'],['跨城冷链',54,'待发 7 条']]
export const issues=[['冷链','跨城路线预计超过冷链交付窗口','建议更换司机并减少中途站点','待审批'],['交通','上海高架拥堵指数升至 0.86','已生成两条备选路线','处理中'],['工时','两名司机当日工时接近上限','已锁定后续派单','已处理']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
